on:
  push:
    branches:
      - main
name: E2E
jobs:
  golangci:
    name: e2etest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: '>=1.17.0'
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
      - uses: actions/checkout@v3
      - name: Create e2etest env
        run: make deploy STAGE=e2etest
      - name: Run e2etests
        run: make e2etest STAGE=e2etest
      - name: Remove e2etest env
        run: make remove STAGE=e2etest
        if: always()