on: [push]
name: CICD
jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/e2e'
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: '>=1.17.0'
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
      - uses: actions/checkout@v3
      - run: make install